import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    //id 'org.springframework.boot' version '3.3.0' // 适当的版本
    //id 'io.spring.dependency-management' version '1.1.7' // 适当的版本
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'java'
    id 'maven-publish'
    id 'application'
}
def baseName = "core"
def mainC = "dev.anye.core.Main"
group = 'dev.anye'
version = '25.06.2900'
archivesBaseName = 'core'
sourceCompatibility = '21' // 适当的 Java 版本
repositories {
    mavenCentral()
}
configurations {
    shadow
}
dependencies {
    //implementation('org.springframework.boot:spring-boot-starter-web')
    implementation("net.java.dev.jna:jna-platform:5.15.0")
    implementation("com.google.code.gson:gson:2.13.1")
    //implementation("org.graalvm.polyglot:polyglot:24.2.1")
    //implementation("org.graalvm.polyglot:js:24.2.1")
    //implementation("org.graalvm.compiler:compiler:24.2.1")

    shadow("org.graalvm.polyglot:polyglot:24.2.1")
    shadow("org.graalvm.polyglot:js:24.2.1")
}

/*
tasks.register('customJar', Jar) {
    archiveBaseName = 'custom-jar-name'
    from(configurations.runtimeClasspath) {
    }

}
        archiveAppendix.set("all")
*/

tasks{
    shadowJar {
        archiveBaseName.set(baseName)
        archiveClassifier.set("mc")
        manifest {
            attributes("Main-Class" : mainC)
        }
        mergeServiceFiles()
        configurations = [project.configurations.shadow]
    }
}



tasks.register('shadowJarAll', ShadowJar) {
    archiveBaseName.set(baseName)
    archiveClassifier.set("all")
    manifest {
        attributes("Main-Class" : mainC)
    }
    mergeServiceFiles()
    configurations = [
            project.configurations.runtimeClasspath,
            project.configurations.shadow
    ]
}
/*
tasks {

}


 */

//./gradlew clean build publishToMavenLocal
publishing {
    publications {
        create('mavenJava', MavenPublication) {
            groupId = group
            artifactId = archivesBaseName
            version = version
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}

/*
tasks.withType(JavaExec).configureEach {
    jvmArgs '-XX:+UnlockExperimentalVMOptions', '-XX:+EnableJVMCI',
            '--upgrade-module-path', configurations.runtimeClasspath.asPath
}

 */
/*
tasks.named("shadowJarAll") {
    dependsOn("classes") // Make sure classes are compiled before building the shadowJar
}

 */
tasks.named("build") {
    dependsOn shadowJarAll // 将 shadowJarAll 添加到 build 任务的依赖项中
    dependsOn publishToMavenLocal
}


application {
    mainClass = 'dev.anye.core.Main'
}